export {
  CHUNK_EDGE,
  CHUNK_VOXEL_COUNT,
  DEFAULT_VOXEL_VOLUME_LIMITS,
  VoxelVolume,
  chunkBounds,
  chunkCoordinate,
  chunkIndex,
  chunkKey,
  localCoordinate,
  type ChunkChange,
  type VoxelChangeSet,
  type VoxelPatch,
  type VoxelVolumeLimits,
  type VoxelVolumeReadView,
  type VoxelWriteCapability,
} from "./volume.js";
