export {
  CHUNK_EDGE,
  CHUNK_VOXEL_COUNT,
  DEFAULT_VOXEL_VOLUME_LIMITS,
  MAX_VOXELS_PER_OPERATION,
  VoxelVolume,
  chunkBounds,
  chunkCoordinate,
  chunkIndex,
  chunkKey,
  localCoordinate,
  type ChunkChange,
  type VoxelChangeSet,
  type VoxelChunkSeed,
  type VoxelEntry,
  type VoxelPatch,
  type VoxelPatchChunk,
  type VoxelPatchTarget,
  type VoxelVolumeLimits,
  type VoxelVolumeReadView,
  type VoxelWriteCapability,
} from "./volume.js";
export {
  boxCoordinates,
  cylinderCoordinates,
  sphereCoordinates,
  type ShapeAxis,
  type ShapeIterationOptions,
} from "./shapes.js";
export {
  assertExactRotationRegion,
  canRotateExactly,
  mirrorCoordinate,
  rotateRegionPlan,
  translateAabb,
  type QuarterTurns,
  type RegionRotationPlan,
} from "./regions.js";
