export {
  CommandBus,
  type HistoryEntryInfo,
  type HistorySnapshot,
} from "./bus.js";
export {
  CommandRegistry,
  type CommandExecution,
  type CommandExecutionContext,
  type CommandHandler,
  type CommandValidationContext,
  type InverseCommand,
} from "./registry.js";
export {
  DEFAULT_COMMAND_LIMITS,
  type Command,
  type CommandLimits,
  type TransactionOptions,
  type TransactionResult,
  type TransactionSuccess,
} from "./types.js";
export {
  runCommandConformanceSuite,
  type CommandConformanceSpec,
  type ConformanceTestApi,
} from "./conformance.js";
export {
  VOXEL_COMMAND_SCHEMA_VERSION,
  VOXEL_REMOVE_COMMAND,
  VOXEL_SET_COMMAND,
  registerVoxelCommands,
  removeVoxelCommand,
  setVoxelCommand,
  type RemoveVoxelPayload,
  type SetVoxelPayload,
} from "./voxel-commands.js";
export {
  VOXEL_APPLY_PATCHES_COMMAND,
  VOXEL_FILL_BOX_COMMAND,
  VOXEL_FILL_CYLINDER_COMMAND,
  VOXEL_FILL_SPHERE_COMMAND,
  VOXEL_REMOVE_BATCH_COMMAND,
  VOXEL_REPLACE_MATERIAL_COMMAND,
  VOXEL_SET_BATCH_COMMAND,
  applyPatchesCommand,
  fillBoxCommand,
  fillCylinderCommand,
  fillSphereCommand,
  registerBatchCommands,
  removeBatchCommand,
  replaceMaterialCommand,
  setBatchCommand,
  type ApplyPatchesPayload,
  type FillBoxPayload,
  type FillCylinderPayload,
  type FillSpherePayload,
  type RemoveBatchPayload,
  type ReplaceMaterialPayload,
  type SetBatchEntry,
  type SetBatchPayload,
} from "./batch-commands.js";
export {
  VOXEL_COPY_REGION_COMMAND,
  VOXEL_DELETE_REGION_COMMAND,
  VOXEL_MIRROR_REGION_COMMAND,
  VOXEL_ROTATE_REGION_COMMAND,
  VOXEL_TRANSLATE_REGION_COMMAND,
  copyRegionCommand,
  deleteRegionCommand,
  mirrorRegionCommand,
  registerRegionCommands,
  rotateRegionCommand,
  translateRegionCommand,
  type CopyRegionPayload,
  type DeleteRegionPayload,
  type MirrorRegionPayload,
  type RotateRegionPayload,
  type TranslateRegionPayload,
} from "./region-commands.js";

export {
  NODE_COMMAND_SCHEMA_VERSION,
  NODE_CREATE_COMMAND,
  NODE_DELETE_COMMAND,
  NODE_RENAME_COMMAND,
  NODE_REPARENT_COMMAND,
  NODE_SET_COMPONENTS_COMMAND,
  NODE_SET_METADATA_COMMAND,
  NODE_SET_TRANSFORM_COMMAND,
  createNodeCommand,
  deleteNodeCommand,
  registerNodeCommands,
  renameNodeCommand,
  reparentNodeCommand,
  setNodeComponentsCommand,
  setNodeMetadataCommand,
  setNodeTransformCommand,
  type CreateNodePayload,
  type DeleteNodePayload,
  type RenameNodePayload,
  type ReparentNodePayload,
  type ReparentPlacement,
  type SetNodeComponentsPayload,
  type SetNodeMetadataPayload,
  type SetNodeTransformPayload,
} from "./node-commands.js";
export {
  MATERIAL_COMMAND_SCHEMA_VERSION,
  MATERIAL_CREATE_COMMAND,
  MATERIAL_DELETE_COMMAND,
  MATERIAL_UPDATE_COMMAND,
  createMaterialCommand,
  deleteMaterialCommand,
  registerMaterialCommands,
  updateMaterialCommand,
  type CreateMaterialPayload,
  type DeleteMaterialPayload,
  type UpdateMaterialPayload,
} from "./material-commands.js";
