import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { canonicalDocumentJson } from "@voxel-maker/model";
import { readVxlProject, seedReadView, writeVxlProject } from "./container.js";

/**
 * Checked-in native `.vxl` corpus (plan S5.12, ticket #12): a byte-stable
 * golden container plus adversarial and compatibility fixtures that the
 * reader must reject with exact stable codes before any data is returned.
 * The corpus lives at ../../../fixtures/native and is generated by
 * scripts/generate-native-fixtures.mjs (which self-checks every file).
 */

const CORPUS_DIR = fileURLToPath(
  new URL("../../../fixtures/native/", import.meta.url),
);
const corpus = JSON.parse(readFileSync(`${CORPUS_DIR}corpus.json`, "utf8")) as {
  golden: {
    file: string;
    documentJson: string;
    semanticHash: string;
    byteLength: number;
    entryCount: number;
  };
  rejected: readonly {
    file: string;
    vector: string;
    family: string;
    code: string;
  }[];
};

/** Asserts that `fn` throws a WorkspaceError with the exact family/code. */
function expectRejected(fn: () => unknown, family: string, code: string): void {
  let thrown: unknown;
  try {
    fn();
  } catch (error) {
    thrown = error;
  }
  if (thrown === undefined) {
    throw new Error(`Expected ${family}/${code}, but nothing was thrown`);
  }
  const actual =
    typeof thrown === "object" && thrown !== null
      ? {
          family: (thrown as { family?: unknown }).family,
          code: (thrown as { code?: unknown }).code,
        }
      : { family: undefined, code: undefined };
  if (actual.family === family && actual.code === code) return;
  throw new Error(
    `Expected ${family}/${code}, got ${String(actual.family)}/${String(
      actual.code,
    )}`,
  );
}

describe("native fixture corpus", () => {
  it("retains a byte-stable golden round-trip container", () => {
    const bytes = readFileSync(`${CORPUS_DIR}${corpus.golden.file}`);
    const loaded = readVxlProject(bytes);

    // The recorded hash and size prove the fixture is the exact writer
    // output for the recorded asset (no silent regeneration drift).
    expect(loaded.semanticHash).toBe(corpus.golden.semanticHash);
    expect(bytes.byteLength).toBe(corpus.golden.byteLength);
    expect(loaded.manifest.entries.length).toBe(corpus.golden.entryCount);

    // Reloaded document must equal the retained canonical document bytes.
    const retained = readFileSync(
      `${CORPUS_DIR}${corpus.golden.documentJson}`,
      "utf8",
    );
    expect(canonicalDocumentJson(loaded.document)).toBe(retained);

    // Writer stability: rebuilding the same asset must reproduce the
    // retained bytes exactly, so an accidental writer change is a failure.
    const rebuilt = writeVxlProject({
      document: loaded.document,
      volumes: new Map(
        [...loaded.volumes.entries()].map(([id, volume]) => [
          id,
          seedReadView(id, volume.chunks),
        ]),
      ),
    });
    expect(Buffer.from(rebuilt).equals(Buffer.from(bytes))).toBe(true);
  });

  it("rejects every adversarial fixture with its expected stable error", () => {
    for (const fixture of corpus.rejected) {
      const bytes = readFileSync(`${CORPUS_DIR}${fixture.file}`);
      expectRejected(() => readVxlProject(bytes), fixture.family, fixture.code);
    }
  });

  it("indexes every checked-in fixture and nothing else", () => {
    const expected = new Set([
      corpus.golden.file,
      corpus.golden.documentJson,
      "corpus.json",
      "README.md",
      ...corpus.rejected.map((fixture) => fixture.file),
    ]);
    const onDisk = new Set(
      readdirSync(CORPUS_DIR).filter((name) => !name.startsWith(".")),
    );
    expect(onDisk).toEqual(expected);
  });
});
